# Generated by Django 3.0.2 on 2020-05-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Square_Denims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Job_Id', models.CharField(max_length=200, unique=True)),
                ('Date', models.DateField(max_length=100)),
                ('Shift', models.CharField(max_length=100)),
                ('Machine_Name', models.CharField(max_length=100)),
                ('Machine_No', models.IntegerField(blank=True, null=True)),
                ('Machine_Part', models.CharField(max_length=100)),
                ('Problem', models.CharField(max_length=100)),
                ('Cause', models.CharField(max_length=100)),
                ('Solution', models.CharField(max_length=100)),
            ],
        ),
    ]
